/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.JOptionPane;

/**
 *
 * @author UBERNEY
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtUsuario1 = new javax.swing.JTextField();
        PassUser = new javax.swing.JPasswordField();
        jLbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnAceptar.setBackground(new java.awt.Color(102, 102, 102));
        BtnAceptar.setFont(new java.awt.Font("Sylfaen", 0, 13)); // NOI18N
        BtnAceptar.setText("Ingresar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 90, 30));

        BtnCancelar.setBackground(new java.awt.Color(102, 102, 102));
        BtnCancelar.setFont(new java.awt.Font("Sylfaen", 0, 13)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 90, 30));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, 30));

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("CONTRASEÑA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, -1));

        TxtUsuario1.setBackground(new java.awt.Color(204, 204, 204));
        TxtUsuario1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        getContentPane().add(TxtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 270, 30));

        PassUser.setBackground(new java.awt.Color(204, 204, 204));
        PassUser.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        getContentPane().add(PassUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 270, 30));

        jLbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo6.png"))); // NOI18N
        getContentPane().add(jLbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        String user="", pass=""; // variables que recibiran el usuario y la contraseña
        user=TxtUsuario1.getText();
        pass=PassUser.getText();
        
        if (user.equalsIgnoreCase("admin")&& pass.equalsIgnoreCase("123")){// condicional para verificar si el usuario y contraseña ingresado es correcto
            Principal pp = new Principal(); // creacion del objeto de tipo principal, lo cual creara nuestra ventana
            pp.setVisible(true); // hara visible nuestra siguiente ventana (la ventana antes creada))
            this.setVisible(false); // esconde la ventana de logueo           
        }
        else {
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorrectos" );  
            TxtUsuario1.setText(""); // limpia el campo de usuario
            PassUser.setText(""); // limpia el campo de la contraseña
        }
        
        if (user.equals("")&& pass.equals("")){
            JOptionPane.showMessageDialog(null, "Por Favor Ingresar Usuario y Contraseña");
        }
        else if (pass.equals("")){
            JOptionPane.showMessageDialog(null, "La Contraseña No Puede Estar En Blanco");           
        }
        
    }//GEN-LAST:event_BtnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JPasswordField PassUser;
    private javax.swing.JTextField TxtUsuario1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbFondo;
    // End of variables declaration//GEN-END:variables
}
